matrix:
  include:
    - os: linux
      language: python
      python: "3.6"

    - os: osx
      osx_image: xcode8.3
      language: python
      python: "3.6"

install:
  - pip install lxml click

script:
  - ./gradlew html
